name: David Bethune
favicon: null
layout_spectrum: 0.20629
typography_spectrum: 0.91386
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#008ffe'
    - '#fe0039'
    - '#fec700'
    - '#120806'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
