name: David Bethune
favicon: null
layout_spectrum: 0.0955134080722928
typography_spectrum: 0.38888384168967605
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8525130739435554
  lightness: 0.9970614369958639
  saturation: 0.4246916596312076
  rhythmicContrast: 0.5034678964875638
purpose: []
